variable "aws_access_key" {
  type    = string
  default = "${env("AWS_ACCESS_KEY")}"
}

variable "aws_ami" {
  type    = string
  default = "${env("AWS_SOURCE_AMI")}"
}

variable "aws_region" {
  type    = string
  default = "${env("AWS_DEFAULT_REGION")}"
}

variable "aws_secret_key" {
  type    = string
  default = "${env("AWS_SECRET_KEY")}"
}

variable "username" {
  type    = string
  default = "${env("SSH_USERNAME")}"
}

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "packer-wordpress ${local.timestamp}"
  instance_type = "t3.micro"
  region        = "${var.aws_region}"
  secret_key    = "${var.aws_secret_key}"
  source_ami    = "${var.aws_ami}"
  ssh_username  = "${var.username}"
  tags = {
    Environment = "Test"
    Name        = "wordpress_latest"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "ansible" {
    use_proxy     = false
    playbook_file = "./playbook.yml"
  }

}