- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    name:
        - nginx
        - mysql-server
        - wget
        - vim
        - openssl
        - python3
        - python3-pip
    state: present

- name: Remove "foo" package
  apt:
    name: apache2
    state: absent

- name: Install pip packages
  pip:
    name:
        - pymysql

- name: Installing php
  apt:
    name:
        - php
        - php-fpm
        - php-common
        - php-gd 
        - php-pdo
        - php-mbstring
        - php-mysqlnd
        - php-bcmath
        - php-json
        - php-soap
        - php-zip
        - php-xml
        - php-xmlrpc   
    state: present

- name: Make sure mysql service is running
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Make sure php-fpm service is running
  systemd:
    name: php8.1-fpm
    state: started
    enabled: yes

- name: Template archive default.conf
  template:
     src: wordpress.conf.j2
     dest: /etc/nginx/conf.d/wordpress.conf

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: restarted